/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorDocente;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class MenuPrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form menuVieweight
     */
    public MenuPrincipalVista() {
        initComponents();
        
        initComponents();
        setTitle("Menu Principal");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        estudiantesMenu = new javax.swing.JMenuItem();
        docentesMenu = new javax.swing.JMenuItem();
        horarioMenu = new javax.swing.JMenuItem();
        salonMenu = new javax.swing.JMenuItem();
        matriculaMenu = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Vistas");

        estudiantesMenu.setText("Estudiantes");
        estudiantesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiantesMenuActionPerformed(evt);
            }
        });
        jMenu1.add(estudiantesMenu);

        docentesMenu.setText("Docentes");
        docentesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentesMenuActionPerformed(evt);
            }
        });
        jMenu1.add(docentesMenu);

        horarioMenu.setText("Horario");
        horarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioMenuActionPerformed(evt);
            }
        });
        jMenu1.add(horarioMenu);

        salonMenu.setText("Salon");
        salonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonMenuActionPerformed(evt);
            }
        });
        jMenu1.add(salonMenu);

        matriculaMenu.setText("Matricula");
        matriculaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaMenuActionPerformed(evt);
            }
        });
        jMenu1.add(matriculaMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estudiantesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiantesMenuActionPerformed

    }//GEN-LAST:event_estudiantesMenuActionPerformed

    private void docentesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentesMenuActionPerformed
        DocenteVista instanciaDV=new DocenteVista();
        ControladorDocente ctrl=new ControladorDocente(instanciaDV);
        
    }//GEN-LAST:event_docentesMenuActionPerformed

    private void horarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioMenuActionPerformed

    }//GEN-LAST:event_horarioMenuActionPerformed

    private void salonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonMenuActionPerformed

    }//GEN-LAST:event_salonMenuActionPerformed

    private void matriculaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaMenuActionPerformed

    }//GEN-LAST:event_matriculaMenuActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem docentesMenu;
    private javax.swing.JMenuItem estudiantesMenu;
    private javax.swing.JMenuItem horarioMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem matriculaMenu;
    private javax.swing.JMenuItem salonMenu;
    // End of variables declaration//GEN-END:variables
}
